site_name: Pebble Framework Documentation
site_url: 'http://localhost:8000'
theme: readthedocs
nav:
    - Home: index.md
    - Setup: Setup.md
    - Router: Router.md
    - AppExec: AppExec.md
    - Special: Special.md
    - Template: Template.md
    - Logging: Logging.md
    - Config: Config.md
    - DB: DB.md
    - Migration: Migration.md
    - Auth: Auth.md
    - ACL: ACL.md
    - ACLRole: ACLRole.md
    - Flash: Flash.md
    - SMTP: SMTP.md
    - CLI: CLI.md
    - Misc: Misc.md
markdown_extensions:
    - footnotes