site_name: Pebble Framework
site_url: 'http://localhost:8000'
theme: material
nav:
    - Home: index.md
    - Setup: Setup.md
    - Router: Router.md
    - AppExec: AppExec.md
    - Special: Special.md
    - Template: Template.md
    - Logging: Logging.md
    - Config: Config.md
    - DB: DB.md
    - Migration: Migration.md
    - Auth: Auth.md
    - ACL: ACL.md
    - ACLRole: ACLRole.md
    - Flash: Flash.md
    - SMTP: SMTP.md
    - CLI: CLI.md
    - Misc: Misc.md
markdown_extensions:
    - footnotes
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
plugins:
    - search
    - alternate-link
extra_css:
    - css/extra.css
